### ISSUE TITLE
Proposal: Linting

### ISSUE THREAD

**Issue by owlishDeveloper** [algorithms-for-fun/algorithms-princeton-coursera#3]
I propose we try Prettier https://prettier.io/docs/en/index.html which we can use to do a pre-commit linting. It has a community plugin for Java: https://prettier.io/docs/en/plugins.html

Prettier can be used as an Idea plugin as well. Let me know what you think

**Comment by aronaks** [comment]
Nice! Let's try it!

When i did research of linters, i came across the following https://spotbugs.github.io/

> SpotBugs checks for more than 400 bug patterns.

it would be interesting to try it as well
